### ISSUE TITLE
Handling of `onupgradeneeded` event should be customizable

### ISSUE THREAD

**Issue by dullbananas** [devashishdxt/rexie#21]

**Comment by devashishdxt** [comment]
Hi. Thanks for creating this issue. Can you explain your use case that requires custom upgrade handling?

**Comment by dullbananas** [comment]
Database upgrades can require more than just the addition and deletion of object stores. They sometimes involve adding fields, merging object stores, changing the layout of an ArrayBuffer field, etc.

**Comment by devashishdxt** [comment]
Hi @dullbananas, this feature will be added to rexie. But, I'm not sure of timeline yet. In the meantime, you can try using [`idb`](https://crates.io/crates/idb) crate which offers similar functionality with support for custom upgrade handlers (but, it has a low level API which is more closer to indexed db API on the browser).

**Comment by jbowens** [comment]
+1 to the utility of custom upgrade handlers. It's necessary to perform arbitrary migrations as data models evolve. I'll check out `idb`.

**Comment by peteringram0** [comment]
I know this is a roadmapped feature but how are people handling this at the moment until v0.5?
