### ISSUE TITLE
Add an option to return the last inserted record

### ISSUE THREAD

**Issue by afidegnum** [devashishdxt/rexie#22]
from the test, I noticed the result returns the last inserted ID which needs to be queried again to get the inserted record. 

Can you please add the option, after adding a record, there should be a possibility to return the last inserted record which can be passed to a live update of records.

**Comment by devashishdxt** [comment]
This crate is a thin wrapper around indexed db. As indexed db does not return back the value, I don't think this crate should. You can easily maintain the last inserted value in your code.
