### ISSUE TITLE
Unable to compile due to tokio dependency mio

### ISSUE THREAD

**Issue by flosse** [devashishdxt/rexie#29]
![Bildschirmfoto vom 2022-11-21 21-51-13](https://user-images.githubusercontent.com/276043/203155882-6411d532-8894-4a97-9f3e-0c38ed74a8b1.png)

Is there a reason to use `tokio`?
Why not use [`futures::channel`](https://docs.rs/futures/latest/futures/channel/index.html)?

**Comment by SionoiS** [comment]
Same here!

**Comment by devashishdxt** [comment]
> ![Bildschirmfoto vom 2022-11-21 21-51-13](https://user-images.githubusercontent.com/276043/203155882-6411d532-8894-4a97-9f3e-0c38ed74a8b1.png)
> 
> Is there a reason to use `tokio`? Why not use [`futures::channel`](https://docs.rs/futures/latest/futures/channel/index.html)?

Hi. Thanks for creating this issue. Can you post the output of `cargo tree --invert tokio --edges features` on your crate?

**Comment by SionoiS** [comment]
```
tokio v1.21.2
├── tokio feature "bytes"
│   ├── tokio feature "io-util"
│   │   └── h2 v0.3.15
│   │       └── h2 feature "default"
│   │           └── hyper v0.14.20
│   │               ├── hyper feature "default"
│   │               │   └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli)
│   │               │       └── cli feature "default" (command-line)
│   │               ├── hyper feature "http1"
│   │               │   └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   │               ├── hyper feature "runtime"
│   │               │   └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   │               ├── hyper feature "server"
│   │               │   └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   │               ├── hyper feature "socket2"
│   │               │   └── hyper feature "tcp"
│   │               │       └── hyper feature "runtime" (*)
│   │               ├── hyper feature "stream"
│   │               │   └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   │               └── hyper feature "tcp" (*)
│   └── tokio feature "process"
│       └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
├── tokio feature "default"
│   ├── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   ├── h2 v0.3.15 (*)
│   ├── hyper v0.14.20 (*)
│   └── tokio-util v0.7.4
│       ├── tokio-util feature "codec"
│       │   └── h2 v0.3.15 (*)
│       ├── tokio-util feature "default"
│       │   └── h2 v0.3.15 (*)
│       └── tokio-util feature "tracing"
│           └── tokio-util feature "codec" (*)
├── tokio feature "io-util" (*)
├── tokio feature "libc"
│   ├── tokio feature "net"
│   │   └── hyper feature "tcp" (*)
│   ├── tokio feature "process" (*)
│   └── tokio feature "signal"
│       └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
├── tokio feature "macros"
│   └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
├── tokio feature "memchr"
│   └── tokio feature "io-util" (*)
├── tokio feature "mio"
│   ├── tokio feature "net" (*)
│   ├── tokio feature "process" (*)
│   └── tokio feature "signal" (*)
├── tokio feature "net" (*)
├── tokio feature "num_cpus"
│   └── tokio feature "rt-multi-thread"
│       └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
├── tokio feature "process" (*)
├── tokio feature "rt"
│   ├── tokio feature "rt-multi-thread" (*)
│   ├── hyper feature "runtime" (*)
│   └── hyper feature "tcp" (*)
├── tokio feature "rt-multi-thread" (*)
├── tokio feature "signal" (*)
├── tokio feature "signal-hook-registry"
│   ├── tokio feature "process" (*)
│   └── tokio feature "signal" (*)
├── tokio feature "socket2"
│   └── tokio feature "net" (*)
├── tokio feature "sync"
│   ├── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   ├── hyper v0.14.20 (*)
│   ├── rexie v0.4.2
│   │   ├── rexie feature "console_error_panic_hook"
│   │   │   └── rexie feature "default"
│   │   │       └── defluencer v0.1.0 (/mnt/Dev/Github/rust-defluencer/defluencer)
│   │   │           └── defluencer feature "default" (command-line)
│   │   │               └── cli v0.1.0 (/mnt/Dev/Github/rust-defluencer/cli) (*)
│   │   └── rexie feature "default" (*)
│   └── tokio-util v0.7.4 (*)
├── tokio feature "time"
│   ├── hyper feature "runtime" (*)
│   └── hyper feature "tcp" (*)
└── tokio feature "tokio-macros"
    └── tokio feature "macros" (*)
```

**Comment by devashishdxt** [comment]
@flosse and @SionoiS. `rexie` only pulls `"sync"` feature of `tokio` (which compiles for `wasm32-unknown-unknown`) as can be seen in dependency graph and [Cargo.toml](https://github.com/devashishdxt/rexie/blob/main/Cargo.toml). Please make sure you're not pulling additional features of `tokio` from other dependencies. If your code builds for both wasm and non-wasm targets, consider using features for them. Here's an example: https://github.com/devashishdxt/stag.

**Comment by devashishdxt** [comment]
> ```
> tokio v1.21.2
> └── tokio feature "sync"
>     └── rexie v0.4.2
>         ├── rexie feature "console_error_panic_hook"
>         │   └── rexie feature "default"
>         │       └── defluencer v0.1.0 (/mnt/Dev/Github/rust-defluencer/defluencer)
>         │           └── defluencer feature "default" (command-line)
>         └── rexie feature "default" (*)
> ```

If this is your complete dependency graph, your crate should ideally compile fine on wasm targets. Can you share your `Cargo.toml` file?

**Comment by devashishdxt** [comment]
@flosse From your dependency graph, I can see that most of the features are pulled by `reqwest` and not `rexie`.

**Comment by SionoiS** [comment]
It's the graph for one crate in my workspace. Will try with flags.

**Comment by SionoiS** [comment]
I'm still investigating but so far ANY tokio uses plus reqwest does not compile... seams like reqwest dep of tokio is not feature gated properly.

This can be close this is a reqwest <-> tokio problem nothing to do with your crate.

**Comment by SionoiS** [comment]
Ok smallest reproducible example. I have a wasm-based website project.

Everything compile fine and ```cargo tree --invert tokio --edges features``` returns nothing.

I then add ```tokio = { version = "1", default-features = false, features = [] }``` as a dep.

```cargo tree --invert tokio --edges features``` returns
```
tokio v1.21.2
└── utils v0.1.0 (/mnt/Dev/Github/social_defluencer/utils)
    └── utils feature "default" (command-line)
```
```cargo build --target=wasm32-unknown-unknown```
```
error: could not compile `mio` due to 44 previous errors
```
How is that even possible???

**Comment by devashishdxt** [comment]
> Ok smallest reproducible example. I have a wasm-based website project.
> 
> 
> 
> Everything compile fine and ```cargo tree --invert tokio --edges features``` returns nothing.
> 
> 
> 
> I then add ```tokio = { version = "1", default-features = false, features = [] }``` as a dep.
> 
> 
> 
> ```cargo tree --invert tokio --edges features``` returns
> 
> ```
> 
> tokio v1.21.2
> 
> └── utils v0.1.0 (/mnt/Dev/Github/social_defluencer/utils)
> 
>     └── utils feature "default" (command-line)
> 
> ```
> 
> ```cargo build --target=wasm32-unknown-unknown```
> 
> ```
> 
> error: could not compile `mio` due to 44 previous errors
> 
> ```
> 
> How is that even possible???

If you're in a workspace, then every dependency is compiled only once. If any other crate in your workspace uses `tokio` with other features, that won't compile for wasm targets.

Consider using dependency resolver `2`.

**Comment by flosse** [comment]
@devashishdxt and @SionoiS thanks for helping out!

**Comment by SionoiS** [comment]
> Consider using dependency resolver 2.

Thank you so much @devashishdxt ! I didn't know that was a thing.
