### ISSUE TITLE
Production usage?

### ISSUE THREAD

**Issue by arctic-hen7** [devashishdxt/rexie#3]
Hi! This crate looks extremely interesting to me, and I'm wondering to what extent you'd say it's production-ready. I understand that it's still in its early versions, but the API looks very promising (and worlds away from the `web_sys` bindings). I don't need something perfectly polished by any means, just something that's reasonably unlikely to blow up in my face.

I'm the developer of [Perseus](https://github.com/arctic-hen7/perseus), and we need to use IndexedDB for app state caching, and a good wrapper for it would be extremely helpful! If you have any particular hurdles that you need to get over before considering this reasonably reliable, I'm happy to assist where I can.

**Comment by devashishdxt** [comment]
This is a very thin wrapper on top of `web-sys` API. I haven't used it in a large project yet, but, I think it should be good to use in production (with sufficient testing). There are a few things this crate doesn't support right now,

- It doesn't expose raw cursor API (it only exposes `get_all` with `limit` and `offset` which is the most common usecase of cursor API).
- It doesn't support creating compound indexes.

If you're not using above two things, then you're good to go.

**Comment by arctic-hen7** [comment]
Fantastic! Thanks so much for the quick reply!
