### ISSUE TITLE
Rexie should not set a panic handler

### ISSUE THREAD

**Issue by arctic-hen7** [devashishdxt/rexie#37]
Right now, `rexie` initializes `console_error_panic_hook` according to the corresponding feature flag, which leads to some very unexpected behavior for end users. For example, [Perseus](https://github.com/framesurge/perseus) (a Rust web framework that uses Rexie for hot state reloading) sets its own panic handler, but this is overridden in development by Rexie's, leading to some extremely strange errors.

I'm not exactly sure what the original rationale was for having this library set a panic handler, but would it be possible to make this feature non-default, if not remove it entirely? Happy to submit a PR if you're happy with this.

Also, thanks for this library, it's been very useful!

**Comment by devashishdxt** [comment]
Fixed in #40
