### ISSUE TITLE
Rexie appears to hang on add()

### ISSUE THREAD

**Issue by iamwilhelm** [devashishdxt/rexie#39]
I was following the example on the README, and while it seems to get through the await in initialization, it appears to get stuck in the await from the `add()`. Noob question: Do I need to have an async runtime already running for this to work? I had assumed no, since I called into the rust async function from javascript in the browser. But I'm not sure as I'm new to WASM.

**Comment by devashishdxt** [comment]
I'm not sure the exact reason you're facing this issue. Can you post some code so that I can debug the issue?
