### ISSUE TITLE
Rexie correctness currently relies on invalid assumptions about the executor

### ISSUE THREAD

**Issue by Ekleog** [devashishdxt/rexie#43]
Currently, `rexie` relies on behavior of the futures executor that is not actually specified: it assumes that waking a task from an IndexedDB callback, and then returning from the IndexedDB callback, will result in the awoken task being executed before returning to the browser event loop.

This is not necessarily true, and in particular breaks with the multi-threaded wasm-bindgen executor. I opened an issue upstream, but unfortunately it seems hard to fix, and was closed as wontfix, because that specific behavior of the singlethread executor was never documented in the first place:
- https://github.com/rustwasm/wasm-bindgen/issues/3798

I'm opening this issue to let you know about this current limitation of rexie. Please don't just comment on the upstream issue without carefully considering whether you're bringing something new to the table, as that would only be bad vibes for the wasm-bindgen maintainers, and they're doing an awesome job.

On my end I'm planning to fix this in my IndexedDB crate via [this change](https://github.com/Ekleog/indexed-db/pull/3) that makes the transaction only ever execute from the callbacks. I verified and it works with the multi-threaded executor, but it also requires a slightly less convenient API. I'm hoping one of the places where I'm opening this issue will have an idea for how to handle this differently :)

Hope that helps!

**Comment by devashishdxt** [comment]
Closing this in favour of https://github.com/devashishdxt/idb/issues/18.
