### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by dariusc93** [devashishdxt/rexie#44]
I came across this repo while looking for other indexeddb wrappers in rust and the API does looks way better than most I've seen or currently use (although I have yet to test rexie yet) but would like to know if this repo is still actively maintained. 

Thanks!

**Comment by devashishdxt** [comment]
> I came across this repo while looking for other indexeddb wrappers in rust and the API does looks way better than most I've seen or currently use (although I have yet to test rexie yet) but would like to know if this repo is still actively maintained. 
> 
> 
> 
> Thanks!

Yes. This repo is actively maintained.

**Comment by devashishdxt** [comment]
On a side note, `idb` crate with `builder` feature also provides similar API.
