### ISSUE TITLE
Objects can't be used as keys

### ISSUE THREAD

**Issue by cypherkitty** [devashishdxt/rexie#49]
Hi, 
I'm trying to use an JsValue object as a key, Rexie can't save that kind of keys.
Here is the example of a key:
```
JsValue(Object({"unit":{"id":{"fqdn":{"objType":"DeviceCreds","objInstance":"index"},"id":0}}}))
```
As you can see, it's just a an object with some fields.
When I try to save a record with the key, I get an error:
```
called `Result::unwrap()` on an `Err` value: IdbError(AddFailed(JsValue(DataError: Failed to execute 'add' on 'IDBObjectStore': The parameter is not a valid key.
Error: Failed to execute 'add' on 'IDBObjectStore': The parameter is not a valid key
```

My question is: is it a natural limitation of indexed db and can rexie do anything with that to make it possible to be able to save records with complex keys?

**Comment by devashishdxt** [comment]
This is not related to `rexie`. IndexedDB only takes specific types as keys. Read more about it in official IndexedDB documentation [here](https://w3c.github.io/IndexedDB/#key-construct).
