### ISSUE TITLE
How does rexie differs from idb?

### ISSUE THREAD

**Issue by LucaCappelletti94** [devashishdxt/rexie#50]
What are the main differences between rexie and idb?

**Comment by devashishdxt** [comment]
Not much (anymore). Initially, `idb` was a wrapper over `web-sys` and `rexie` offered a builder pattern for creating object stores. Later, the builder pattern was merged in `idb` under builder feature (which `rexie` now uses).

**Comment by LucaCappelletti94** [comment]
Ok, thank you for your explanation!
